export * from "./admin/films";
export * from "./admin/purchases/PurchasesManagement";
export * from "./admin/users";
export * from "./user/UserDashboard";
export * from "./Dashboard";
export * from "./Login";
export * from "./NotFound";
export * from "./Register";
export * from "./Unauthorized";