export enum FilmClassification {
    ALL_AUDIENCES = "ALL_AUDIENCES",
    SEVEN_YEARS = "SEVEN_YEARS",
    TWELVE_YEARS = "TWELVE_YEARS",
    FIFTEEN_YEARS = "FIFTEEN_YEARS",
    EIGHTEEN_YEARS = "EIGHTEEN_YEARS"
}