version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: film-management-back
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_NAME=${DB_NAME:-films_db}
      - DB_HOST=db:5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - FIREBASE_CREDENTIALS_PATH=${FIREBASE_CREDENTIALS_PATH}
      - FIREBASE_BUCKET_NAME=${FIREBASE_BUCKET_NAME}
    volumes:
      - ./${FIREBASE_CREDENTIALS_PATH}:/app/${FIREBASE_CREDENTIALS_PATH}
    networks:
      - film-management-network

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${DB_NAME:-films_db}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - film-management-network

networks:
  film-management-network:
    driver: bridge

volumes:
  postgres-data: